/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controle_salgados;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author JoãoFontes
 */
public class Interface extends javax.swing.JFrame {


     
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etchedBorder1 = (javax.swing.border.EtchedBorder)javax.swing.BorderFactory.createEtchedBorder();
        pastel = new javax.swing.JButton();
        javax.swing.JButton coxinha = new javax.swing.JButton();
        sanduiche = new javax.swing.JButton();
        lbl_Sair = new javax.swing.JButton();
        lbl_Limpar = new javax.swing.JButton();
        lbl_Coxinha = new javax.swing.JLabel();
        lbl_Pastel = new javax.swing.JLabel();
        lbl_Americano = new javax.swing.JLabel();
        lbl_Valor01 = new javax.swing.JLabel();
        lbl_Valor02 = new javax.swing.JLabel();
        lbl_nomeCoxinha = new javax.swing.JLabel();
        lbl_PastelGenovesa = new javax.swing.JLabel();
        lbl_Sanduíche = new javax.swing.JLabel();
        lbl_Valor03 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fundo2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pastel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PASTEIZINHOSGENOVESA (1).jpg"))); // NOI18N
        pastel.setText("jButton3");
        pastel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pastel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastelActionPerformed(evt);
            }
        });
        getContentPane().add(pastel, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 179, 123, 154));

        coxinha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Coxinha.jpg"))); // NOI18N
        coxinha.setText("jButton1");
        coxinha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        coxinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coxinhaActionPerformed(evt);
            }
        });
        getContentPane().add(coxinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 179, 123, 154));

        sanduiche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sandwichNatural (2).jpg"))); // NOI18N
        sanduiche.setText("jButton2");
        sanduiche.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sanduiche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sanduicheActionPerformed(evt);
            }
        });
        getContentPane().add(sanduiche, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 179, 123, 154));

        lbl_Sair.setBackground(new java.awt.Color(60, 63, 65));
        lbl_Sair.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        lbl_Sair.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Sair.setText("Sair");
        lbl_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_SairActionPerformed(evt);
            }
        });
        getContentPane().add(lbl_Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 60, -1));

        lbl_Limpar.setBackground(new java.awt.Color(51, 51, 51));
        lbl_Limpar.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        lbl_Limpar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Limpar.setText("Limpar");
        lbl_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_LimparActionPerformed(evt);
            }
        });
        getContentPane().add(lbl_Limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 80, -1));

        lbl_Coxinha.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Coxinha.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        lbl_Coxinha.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Coxinha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Coxinha.setText("Saidas");
        lbl_Coxinha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lbl_Coxinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 60, 30));

        lbl_Pastel.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Pastel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        lbl_Pastel.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Pastel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Pastel.setText("Saidas");
        lbl_Pastel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbl_Pastel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(lbl_Pastel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 358, 60, 30));

        lbl_Americano.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Americano.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        lbl_Americano.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Americano.setText("Saidas");
        lbl_Americano.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lbl_Americano, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 358, 60, 30));

        lbl_Valor01.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Valor01.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        lbl_Valor01.setForeground(new java.awt.Color(51, 51, 51));
        lbl_Valor01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Valor01.setText("0");
        lbl_Valor01.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lbl_Valor01, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 50, 30));

        lbl_Valor02.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Valor02.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        lbl_Valor02.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Valor02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Valor02.setText("0");
        lbl_Valor02.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lbl_Valor02, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 50, 30));

        lbl_nomeCoxinha.setBackground(new java.awt.Color(255, 255, 255));
        lbl_nomeCoxinha.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        lbl_nomeCoxinha.setForeground(new java.awt.Color(204, 204, 204));
        lbl_nomeCoxinha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_nomeCoxinha.setText("COXINHA VEGANA");
        getContentPane().add(lbl_nomeCoxinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 110, -1));

        lbl_PastelGenovesa.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        lbl_PastelGenovesa.setForeground(new java.awt.Color(204, 204, 204));
        lbl_PastelGenovesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_PastelGenovesa.setText("PASTEIZINHOS À GENOVESA");
        getContentPane().add(lbl_PastelGenovesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        lbl_Sanduíche.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        lbl_Sanduíche.setForeground(new java.awt.Color(204, 204, 204));
        lbl_Sanduíche.setText("SANDUÍCHE NATURAL");
        getContentPane().add(lbl_Sanduíche, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        lbl_Valor03.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Valor03.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        lbl_Valor03.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Valor03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Valor03.setText("0");
        lbl_Valor03.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lbl_Valor03, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 50, 30));

        jLabel1.setFont(new java.awt.Font("NSimSun", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tem Prazeres");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 16, 241, 52));

        fundo2.setBackground(new java.awt.Color(101, 173, 129));
        fundo2.setForeground(new java.awt.Color(101, 173, 129));
        fundo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo2 (1).jpg"))); // NOI18N
        fundo2.setLabelFor(sanduiche);
        fundo2.setVerifyInputWhenFocusTarget(false);
        fundo2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fundo2PropertyChange(evt);
            }
        });
        getContentPane().add(fundo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle_salgados/papel-de-amoreira-texturizado.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(632, 460));
        jLabel2.setMinimumSize(new java.awt.Dimension(632, 460));
        jLabel2.setPreferredSize(new java.awt.Dimension(632, 460));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_lbl_SairActionPerformed

    private void coxinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coxinhaActionPerformed
        Contagem_Salgados contadorCoxinha = new Contagem_Salgados();
        
        Contagem_Salgados.adicionarCoxinha(1);
        String contString = String.valueOf(contadorCoxinha.getContadorCoxinha());
        lbl_Valor01.setText(contString);
    
        
        
    }//GEN-LAST:event_coxinhaActionPerformed

    private void sanduicheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sanduicheActionPerformed
        
         Contagem_Salgados contadorSanduiche = new Contagem_Salgados();
        
        Contagem_Salgados.adicionarSanduiche(1);
        String contString = String.valueOf(contadorSanduiche.getContadorSanduiche());
        lbl_Valor02.setText(contString);
        
        
        
        
        
//        Contagem_Salgados contadorSanduiche = new Contagem_Salgados();
//        
//        contadorSanduiche.setContadorSanduiche(1);
//        String contString = String.valueOf(contadorSanduiche.getContadorSanduiche());
//        lbl_Valor02.setText(contString);
    }//GEN-LAST:event_sanduicheActionPerformed

    private void fundo2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fundo2PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_fundo2PropertyChange

    private void pastelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastelActionPerformed
        Contagem_Salgados contadorPastel = new Contagem_Salgados();
        
        Contagem_Salgados.adicionarPastel(1);
        String contString = String.valueOf(contadorPastel.getContadorPastel());
        lbl_Valor03.setText(contString);
    }//GEN-LAST:event_pastelActionPerformed

    private void lbl_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_LimparActionPerformed
        Contagem_Salgados.limparContador(); 
        lbl_Valor01.setText("0");
        lbl_Valor02.setText("0");
        lbl_Valor03.setText("0");
        
    }//GEN-LAST:event_lbl_LimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
                
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.border.EtchedBorder etchedBorder1;
    private javax.swing.JLabel fundo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_Americano;
    private javax.swing.JLabel lbl_Coxinha;
    private javax.swing.JButton lbl_Limpar;
    private javax.swing.JLabel lbl_Pastel;
    private javax.swing.JLabel lbl_PastelGenovesa;
    private javax.swing.JButton lbl_Sair;
    private javax.swing.JLabel lbl_Sanduíche;
    private javax.swing.JLabel lbl_Valor01;
    private javax.swing.JLabel lbl_Valor02;
    private javax.swing.JLabel lbl_Valor03;
    private javax.swing.JLabel lbl_nomeCoxinha;
    private javax.swing.JButton pastel;
    private javax.swing.JButton sanduiche;
    // End of variables declaration//GEN-END:variables
}
